services:
  syncify:
    image: github.com/thechubbypanda/syncify:dev
    container_name: syncify
    network_mode: host
    env_file:
      - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./cmd
          target: /app/cmd
        - action: sync+restart
          path: ./internal
          target: /app/internal
        - action: sync+restart
          path: ./static
          target: /app/static
        - action: sync+restart
          path: ./go.mod
          target: /app/go.mod
        - action: sync+restart
          path: ./go.sum
          target: /app/go.sum
        - action: sync+restart
          path: ./tailwind.css
          target: /app/tailwind.css
        - action: rebuild
          path: package.json
          target: /app/package.json
        - action: rebuild
          path: ./Dockerfile
          target: /app/Dockerfile

