services:
  syncify:
    image: ghcr.io/thechubbypanda/syncify:main
    build: .
    restart: unless-stopped
    user: 1000:1000 # Change to your user
    env_file:
      - .env
    ports:
      - 8000:8000
